language: java
dist: trusty
jdk: openjdk8
sudo: false
install: true
jobs:
  include:
  - stage: test
    script:
    - mvn -f fr.ibp.odv.boem.parent clean test
  - stage: deploy
    if: branch = master
    script:
    - mvn -f fr.ibp.odv.boem.parent install
    - chmod +x pushToBintray.sh
    - "./pushToBintray.sh boem-nightly nightly releng/fr.ibp.odv.boem.updatesite/target/repository"
env:
  global:
  - BINTRAY_OWNER=i-bp
  - BINTRAY_REPO=boem
  #BINTRAY_USER=xxx
  - secure: hQbwz5E8dvXtIagri2F8uloKD3Cvos/FxWMFbrXeVtWz4+QwY4nTS69zrh3nX1kbgSbwf9pUncIb+iQIFYSQmnu/eYL1vxL0VctaQjsPEIcKihxTyZvCmeaYsT5qh8i43RlDqViTWI3WK4t9KNEkpQ/s8kaUXxKb37jxaIiBXzmwKYZv5UzsjQXmX8ekCgul0xjolYtVXXU5fenQxzk5G+ivzoX5DBeybz4GrFWhWrHkVsv2fP9ikjEq6hYcdWQaW1DcI4wS1OnVGgwPKf6Wk9ByoYzIt1akyfdYoH+kim74w4CvQe5EY+cYxt9IZkqbWsVoPmj+qjkTR6Nxo+U07H+vLCXhA7JxO24S5l/bx5UQDQwoZazcj51MRCt+W4gy1ydskFTJz38HG3ZdI/UNoD94st3UMHJLIorscj7w6R/i41ZWihO8eDmzm/4FFhM7UgW41Tg818MxEtyke7fRuBnJfPuBXFPwfkT/KAl05mkhNUGDRVFczm4y3fePQRna8LyrSXBJYdqdB1ZVRTGawe3Sh0jnoxZLOyFPD9AfTrThnZKnuWqGq2gpJg/CAjYxK+OEqoUF/xTQRRarEL4e+1EAaEP16L4QPRtCSnkfV8+JmVDjydC57/H8Ps5g4oN2Ua4mGVxjDOZ4KSmjw3T2o6JBismitrbQy8eactIVtPk=
  #BINTRAY_API_KEY=yyy
  - secure: wYu6uTC2PDjAPPGF2uGHCFIoywDuJJkUZ6yNMjA6+C7uop31odSO6D11l5MwzI3nKXmDDOU/LnPHpmv7nVm0iaZPQ+/ZV1kURR5N2hzKbywxTQTcap5njbEtsTG5qL6CzqIm0YY+0HC34hlExcOZdQAIlEy6ZIpLrIttzhDKv1WtrU0JvHEUupO2dUsubGEhlB1+UNPWsKMJamsRhRzGwwttXvhdIC/+sU+Iuqbj6qdC1VPKWrCIoPPe4vMiHkeDYwvWC0MH/VYJP50KshBCvudD4DjlsxhCRBJ5CcHWXUzLLqARWBiHremYOQzPQafe3htASqt4swXNNvhhc8tkD72A1/MHeDHgPq8CwLNGo6KXGZ41fAjyblNi2mtKMnZ2sYeM5p9ZGXnSt0BmfycZKSiEp3ZhuE5DsvSWAjHlD9KGI+I492+bj0FIZD2reZOzRQ+gf+Zm9UwJsvxWIRuyKfSILy4cGOK9UO48jNXtiN6MZ0PYRsX7BfSpOpFHpnX+V88Yxr33CqQ2dwm1qtdUsbBbRsxOdSRLCf+7P3RVk16+rBciYOYE1j+LYq6BVWplDiQx0IVg7rU8c9kJJolaBFl2zVZE+rlULVI+DLexLNqFbh6s5rUbmMF7LZLqNhyZL6OpcLsDHeiZGZwkJwbhZE8rVF1EGbFIpL9l+Ib+GM4=
